### ISSUE TITLE
Enable pip Installation

### ISSUE THREAD

**Issue by mmaleki92** [jcanivete/swirl#2]
Hello,

I've recently begun using the swirl module in my projects and have found it to be extremely useful and well-written. However, I noticed that the module isn't currently available for installation via pip, which could make it more accessible to a wider audience.

Is there a specific reason for its absence from PyPI? If not, I would like to propose contributing to the project by making it pip-installable. This would simplify the installation process significantly and could increase its adoption.

Thank you for considering this enhancement.

**Comment by jcanivete** [comment]
Hi @mmaleki92, 

no specific reason, just lack of time. :) If you want to contribute you are very welcome to do so and I would greatly appreciate it.

Cheers,

**Comment by mailhexu** [comment]
Hello,
I didn't notice this issue but I also hope for the same thing.  So I added a pyproject.toml file in this merge request. 
https://github.com/jcanivete/swirl/pull/3
I also added a script for uploading it to pypi (upload_to_pip.sh). So the only thing needed is to have an pypi account and configure locally. 

The problem is that there is a different package named swirl on pypi already, so you might need to give a different name to it. 
Best regards, 
HeXu

**Comment by mmaleki92** [comment]
Hello,
I see, so I am on a trip now, I will work on it this weekend,
so essentially, it just needs a name and some configurations. I'll inform you here.

Thanks

Best regards,
Morteza

**Comment by jcanivete** [comment]
Hi HeXu and Morteza, 
thank you both for your interest and your help. I'm very happy to see that my code is somehow helpful to other people and other scientific communities. :-) 

Regarding the upload to PyPI, I'm totally in favour. However, would it be possible to change the name of the package only on PyPI, i.e. keep this repository as it is? I ask this because I have direct references to this repo (/github.com/jcanivete/swirl) in my papers. Therefore, I would like to keep the link to the code as it is. 

Another question. To upload it on PyPI I guess it would need a requirements.txt file, right?

Cheers,
Roberto

**Comment by mailhexu** [comment]
Hi Roberto, 
It is possible to only change the name of the package on pypi only. The only thing to do is to modify the line 
```name = swirl ```
in pyproject.yaml when uploading it. 

And when installing the package from pypi,  use:
```pip install NEW_NAME```
Then when import the package,  use
```import NEW_NAME ```
instead of 
``` import swirl```
With the updated pyproject.toml, the procedure to upload to pip is :
- Get an account on pypi
- Get your token from pypi
- add a config file  ~/.pypirc in the home directory (there are other ways but I think this is the easiest). 
- put the following lines to  .pypirc
```
  [pypi]
   username = __token__
  password = YOUR_TOKEN_FROM_PYPI
```
- install the package build and twine with
```
pip install build twine
``` 
- Then run the script
``` sh upload_to_pip.sh```

Hope this helps.
Cheers, 
HeXu

**Comment by jcanivete** [comment]
Hi Hexu and Morteza, 

I uploaded the package to pypi and now it is be possible to install it via:
```
pip install swirl-code
```
Thank you both for your support and help, I really appreciated it! 
If you have any other suggestions to improve the code or need any help, please just let me know. 

Cheers,
Roberto
